# Generated by Django 2.2 on 2020-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(
                choices=[
                    ('FR', 'Freshman'),
                    ('SO', 'Sophomore'),
                    ('JR', 'Junior'),
                    ('SR', 'Senior')
                ],
                default='FR',
                max_length=2
            ),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
