# Generated by Django 2.2 on 2020-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=24),
        ),
    ]
