# Generated by Django 2.2 on 2020-05-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200515_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
                ('execution_time', models.DecimalField(decimal_places=4, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
