# Generated by Django 2.2 on 2020-05-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='', max_length=24),
        ),
    ]
